// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3082.RecycleBot.subsystems;

import org.usfirst.frc3082.RecycleBot.Robot;
import org.usfirst.frc3082.RecycleBot.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Elevator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController elevatorMotorController = RobotMap.elevatorElevatorMotorController;
    Encoder elevatorEncoder = RobotMap.elevatorEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    protected double currentPosition = 0;
    //this is not the correct radius, but we'll need to multiply the ticks by the radius to get the position of the 
    //elevator
    protected double radius = 2.5;
    //get position from bottom of the elevator track
    public void getPosition(){
    	currentPosition = elevatorEncoder.getDistance() * radius;
    }
    public void move(double direction){
    	Robot.elevator.elevatorMotorController.set(direction);
    }
    public void stop(){
    	Robot.elevator.elevatorMotorController.set(0);
    }
}

