// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3082.RecycleBot;
    

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.*;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainLeftFront;
    public static SpeedController drivetrainLeftBack;
    public static SpeedController drivetrainRightFront;
    public static SpeedController drivetrainRightBack;
    public static RobotDrive drivetrainRobotDrive;
    public static SpeedController elevatorElevatorMotorController;
    public static SpeedController grabberGrabberMotor;
    public static Encoder elevatorEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftFront = new Talon(0);
        LiveWindow.addActuator("Drivetrain", "LeftFront", (Talon) drivetrainLeftFront);
        
        drivetrainLeftBack = new Talon(1);
        LiveWindow.addActuator("Drivetrain", "LeftBack", (Talon) drivetrainLeftBack);
        
        drivetrainRightFront = new Talon(2);
        LiveWindow.addActuator("Drivetrain", "RightFront", (Talon) drivetrainRightFront);
        
        drivetrainRightBack = new Talon(3);
        LiveWindow.addActuator("Drivetrain", "RightBack", (Talon) drivetrainRightBack);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainLeftFront, drivetrainLeftBack,
              drivetrainRightFront, drivetrainRightBack);
        
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);

        elevatorElevatorMotorController = new Talon(5);
        LiveWindow.addActuator("Elevator", "ElevatorMotorController", (Talon) elevatorElevatorMotorController);
        
        grabberGrabberMotor = new Talon(4);
        LiveWindow.addActuator("Grabber", "GrabberMotor", (Talon) grabberGrabberMotor);
        elevatorEncoder = new Encoder(0,1,false,Encoder.EncodingType.k4X);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
